services:
  postgresql:
    image: bitnami/postgresql:17
    networks:
      - p2p-education
    restart: "on-failure"
    environment:
      - POSTGRESQL_USERNAME=p2p_edu_user
      - POSTGRESQL_PASSWORD=p2p_edu_password
    ports:
      - "25432:5432"
    expose:
      - 5432
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgresql-storage:/bitnami/postgresql

  keycloak:
    image: bitnami/keycloak:latest
    networks:
      - p2p-education
    restart: "on-failure"
    depends_on:
      - postgresql
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=p2p_edu_user
      - KEYCLOAK_DATABASE_PASSWORD=p2p_edu_password
    ports:
      - "8888:8080"
      - "8443:8443"
    expose:
      - 8080
      - 8443
    volumes:
      - keycloak-storage:/bitnami/keycloak

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile

    networks:
      - p2p-education
    restart: "on-failure"
    depends_on:
      - postgresql
      - keycloak
    environment:
      - JDBC_URL=jdbc:postgresql://postgresql:5432/p2p_education
      - JDBC_USERNAME=p2p_edu_user
      - JDBC_PASSWORD=p2p_edu_password
    ports:
      - "8080:8080"
    expose:
      - 8080


networks:
  p2p-education:
    driver: bridge

volumes:
  postgresql-storage:
  keycloak-storage:
